Add missing deps to //chrome/browser/safe_browsing
Missing deps in //chrome/browser/safe_browsing were leading to error messages
like the following:

obj/chrome/browser/safe_browsing/safe_browsing/chrome_password_protection_service.o
 In file included from ../../chrome/browser/safe_browsing/chrome_password_protection_service.cc:102:
 In file included from ../../brave/chromium_src/chrome/browser/ui/views/frame/browser_view.h:9:
 ../../brave/browser/ui/brave_browser_window.h:12:10: fatal error: 'brave/components/brave_wayback_machine/buildflags/buildflags.h' file not found
    12 | #include "brave/components/brave_wayback_machine/buildflags/buildflags.h"
       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1 error generated.